### ISSUE TITLE
Package installation with pip --require-hashes mode breaks dependencies on install

### ISSUE THREAD

**Issue by defarbs** [blacklanternsecurity/MANSPIDER#26]
Upon attempting a default install with the below `pip` command:
`python3 -m pip install -r requirements.txt`
I am receiving the following error:
```
Collecting tzdata
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    tzdata from https://files.pythonhosted.org/packages/71/9b/8b9fea4f4dc956de76baa291cec1c864a8edadf2950d1740bc386d7fe55a/tzdata-2022.2-py2.py3-none-any.whl#sha256=c3119520447d68ef3eb8187a55a4f44fa455f30eb1b4238fa5691ba094f2b05b (from pytz-deprecation-shim==0.1.0.post0->-r requirements.txt (line 403))
```
I resolved this issue by flagging my original command with `--no-deps`, which (accordingly to official `pip` documentation, will proceed with the install and "Ignore package dependencies". This does not appear to be a long-term fix, but it should resolve the issue for anyone attempting to install requirements for the tool.

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/MANSPIDER/commit/31a6d948755a98ef7a09083e715ac48a09ca2368.
