### ISSUE TITLE
Pipx ERROR: No matching distribution found for man-spider

### ISSUE THREAD

**Issue by jsarkisian** [blacklanternsecurity/MANSPIDER#3]
The following error is present when running `pipx install man-spider`

`ERROR: No matching distribution found for man-spider`

Thanks!

**Comment by TheTechromancer** [comment]
What is your OS? What version of python are you using?

**Comment by jsarkisian** [comment]
Apologies... figured it may be a repo issue or something not related to specific OS, my bad!

`5.6.0-kali2-amd64 #1 SMP Debian 5.6.14-1kali1 (2020-05-25) x86_64 GNU/Linux`

Python 3.8.7

**Comment by TheTechromancer** [comment]
Fixed in eaaf94c509c77b200c914d1f299470998aade25c.
