### ISSUE TITLE
manspider.py Module Import Error

### ISSUE THREAD

**Issue by jsarkisian** [blacklanternsecurity/MANSPIDER#4]
When running man_spider.py, a module import error takes place:

`Traceback (most recent call last):
    File "/root/tools/MANSPIDER/man_spider/manspider.py", line 8, in <module>
       from .lib import *
ImportError: attempted relative import with no known parent package`

The fix is to remove the `.` in `.lib`

Thanks!

**Comment by TheTechromancer** [comment]
Removing the `.` in lib breaks PyPi compatibility but this is an acceptable fix if pip/pipx is not being used.
