### ISSUE TITLE
why this packages install after then why this package is uninstalling try to not install package if there already exists in your system try to fix that

### ISSUE THREAD

**Issue by dhrruvin** [blacklanternsecurity/MANSPIDER#6]
![issue](https://user-images.githubusercontent.com/49072279/124550308-1a994600-de4e-11eb-90e4-100c05768e36.PNG)

**Comment by TheTechromancer** [comment]
![tumblr_mfoz1o01eT1qj1svso1_400](https://user-images.githubusercontent.com/20261699/126386795-4403e922-d12e-4319-a5e9-765d3f2a1ecd.gif)
