### ISSUE TITLE
Error on /lib/file.py , cant find downloading directory

### ISSUE THREAD

**Issue by DIEGOD79** [blacklanternsecurity/MANSPIDER#8]
On 37 line:
self.tmp_filename = Path('/tmp/manspider') / (random_string(15) + file_suffix)

should be:
self.tmp_filename = Path('/tmp/.manspider') / (random_string(15) + file_suffix)

**Comment by TheTechromancer** [comment]
Thanks! Fixed in 7f9495e963fc285589df1af3c979ed47902253cb.
