### ISSUE TITLE
[Feature request] Add support for other authentication methods (PtH, OPtH, PtT, ...)

### ISSUE THREAD

**Issue by ShutdownRepo** [blacklanternsecurity/MANSPIDER#9]
Hey there :wave: Great tool, awesome work!
Since  you base your code on Impacket, adding support for Pass-the-Hash, Overpass-the-Hash, Kerberos auth, Pass-the-Ticket shouldn't be too hard and could make this tool a Snaffler-like for UNIX-only penetration testers.
Since you probably know your code more than I do, here is a feature request but I'd be glad to help you out in this quest :wink: do hesitate to reach out ([https://twitter.com/_nwodtuhs](https://twitter.com/_nwodtuhs))

**Comment by TheTechromancer** [comment]
Thanks for the suggestion. This tool already supports pass-the-hash, and although there currently aren't any plans to implement the other methods, pull requests are always welcome!

**Comment by ShutdownRepo** [comment]
Awesome :+1: adding your tool to [thehacker.recipes](https://www.thehacker.recipes/) and [Exegol](https://github.com/ShutdownRepo/Exegol)! Will PR when I find some time :wink:
